version: '3.8'

services:
  redis:
    image: redis:6-alpine

  web:
    build: ./web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./web/:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: ./web
    command: celery -A main.celery worker --loglevel=info
    volumes:
      - ./web/:/app
    depends_on:
      - redis
    scale: 4

  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis